### ISSUE TITLE
Week 2 review

### ISSUE THREAD

**Issue by hoksilato** [ngray1747/grabvn-golang-bootcamp#1]
Hi @ngray1747, good work and thank you for your submission. Because you didn't create a PR so that I have to review your week 2 assignment in this issue. Hope you'll do it correctly for next week assignment.

### Reviews

- https://github.com/ngray1747/grabvn-golang-bootcamp/blob/master/hello-world.go#L124 `regexp.Compile` has very poor performance, you should create a global variable or inject as input.
- https://github.com/ngray1747/grabvn-golang-bootcamp/blob/master/hello-world.go#L128 because there are some people often don't add space between `.` and the next word. I suggest you remove/replace special characters first with whitespace and then you can use `strings.Fields` to split and remove trailing spaces.
- Your [`readFile`](https://github.com/ngray1747/grabvn-golang-bootcamp/blob/master/hello-world.go#L134) function and [`wordCount`](https://github.com/ngray1747/grabvn-golang-bootcamp/blob/master/hello-world.go#L29) both use `strings.Fields`, this is duplicated, I think you should refactor these two to only call `strings.Fields` only one times.
- https://github.com/ngray1747/grabvn-golang-bootcamp/blob/master/hello-world.go#L156 you may like to define this variable as a constant for easier code maintenance.

**Comment by duyndh** [comment]
Hi @hoksilato , thank you for taking your time to review my assignment and Im so sorry for not creating PR. I have checked back my code about the issues you mentioned and I really appreciate your advice 👍 .
